---
title: The Journey
owner: Thales Aguiar
baseurl: ""
desc: A log of my journey that I will get to the end, and which I hope to be
  only the begining...
about: I am Doctorate Student in Computer Science at the Federal University of
  Rio Grande do Norte. My topics of interest are mainly math, python, data
  science and machine learning; specially in problems related to voice and
  speech.
image: assets/imgs/profile-round-90.png
excerpt_separator: "<!-- more -->"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins: [jekyll-paginate]
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
permalink: pretty
