---
title: The Journey
owner: Thales Aguiar
baseurl: "/thalesaguiar.github.io"
desc: A log of my journey that I will get to the end, which I hope to be the beggining...
about: I am Doctorate Student at the Federal University of Rio Grande do Norte
image: https://i.imgur.com/keDw5XC.png 
excerpt_separator: "<!-- more -->"
markdown: kramdown
plugins: [jekyll-paginate]
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 5
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
